Repository codeit-sprint-fullstack/2-Sprint-Mission-FE, pull requests merged in 2024-08, with the labels that each got.

#12 [김영은] Sprint1&2
  README.md
  bottom-banner.png
  faq/index.html
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  items/index.html
  login-button.png
  login/images/google.png
  login/images/invisible.png
  login/images/kakao.png
  login/images/logo.png
  login/index.html
  login/style.css
  logo.png
  main-banner.png
  privacy/index.html
  reset.css
  sbanner1.png
  sbanner2.png
  sbanner3.png
  shop-button.png
  signup/images/google.png
  signup/images/invisible.png
  signup/images/kakao.png
  signup/images/logo.png
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#17 [양가현] Sprint 1 & 2
  README.md
  faq.html
  images/home/bottom_banner.png
  images/home/footer.png
  images/home/hotitem.png
  images/home/register.png
  images/home/search.png
  images/home/top_banner.png
  images/icon/facebook.png
  images/icon/favicon.ico
  images/icon/instagram.png
  images/icon/pandalogo.png
  images/icon/twitter.png
  images/icon/youtube.png
  images/logo/panda-market-logo.png
  images/sign/btnpassword.png
  images/sign/googlelogo.png
  images/sign/kakaologo.png
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/reset.css
  styles/sign.css
Labels: 매운맛 🔥, 최종 제출

#4 [서유림] Sprint 1+2
  README.md
  faq/index.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/btn_visibility_on_24px.svg
  images/google_logo.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/kakaotalk_logo.png
  images/logo.png
  index.html
  items/index.html
  login/index.html
  login/login.css
  privacy/indedx.html
  reset.css
  signup/index.html
  signup/signup.css
  style.css
Labels: 순한맛 🐑, 최종 제출

#5 [김태영] Sprint 1+2
  README.md
  faq/index.html
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  signup/index.html
  src/Image/GoogleBtn.png
  src/Image/Img_home_01.png
  src/Image/Img_home_02.png
  src/Image/Img_home_03.png
  src/Image/Img_home_bottom.png
  src/Image/Img_home_top.png
  src/Image/KakaoTalkBtn.png
  src/Image/Property 1=md.png
  src/Image/btn_large.png
  src/Image/btn_small_48.png
  src/Image/btn_visibility_off_24px.png
  src/Image/btn_visibility_on_24px.png
  src/Image/ic_facebook.png
  src/Image/ic_instagram.png
  src/Image/ic_twitter.png
  src/Image/ic_youtube.png
  src/Image/logo.png
  src/css/header.css
  src/css/palette.css
  src/css/reset.css
  src/css/style_login.css
  src/css/style_root.css
  src/css/style_signup.css
Labels: 매운맛 🔥, 최종 제출

#16 [서지우] Sprint 1 + 2
  README.md
  SprintStyle.css
  images/blindeye.png
  images/facebook.png
  images/google.png
  images/instagram.png
  images/kakao.png
  images/lets-see.png
  images/panda.png
  images/popular.png
  images/search.png
  images/sellproduct.png
  images/toppanda.png
  images/twitter.png
  images/youtube.png
  images/중고거래.png
  index.html
  login/index.html
  login/loginstyle.css
  signup/index.html
  signup/signupstyle.css
Labels: 매운맛 🔥, 최종 제출

#10 [신지원] Sprint 1+2
  .github/pull-request-template.md
  .vscode/settings.json
  assets/fonts/ROKAFSans.ttf
  assets/img/Img_home_01.png
  assets/img/Img_home_02.png
  assets/img/Img_home_03.png
  assets/img/Img_home_bottom.png
  assets/img/Img_home_top.png
  assets/img/ic_facebook.png
  assets/img/ic_instagram.png
  assets/img/ic_twitter.png
  assets/img/ic_youtube.png
  assets/img/login/btn_visibility_on.png
  assets/img/login/google.png
  assets/img/login/kakao.png
  assets/img/login/판다 얼굴.png
  assets/img/판다 얼굴.png
  faq.html
  index.html
  items.html
  login.css
  login.html
  main.css
  privacy.html
  reset.css
  signin.html
Labels: 매운맛 🔥, 최종 제출

#27 [양가현] Sprint 1 & 2
  README.md
  images/sign/password-active-toggle.png
  index.html
  login.html
  signup.html
  styles/reset.css
  styles/sign.css
Labels: 매운맛 🔥, 최종 제출

#1 [조두현] Sprint1 & 2
  .github/pull-request-template.md
  README.md
  sprint1and2/faq.html
  sprint1and2/img/GoogleIcon.png
  sprint1and2/img/KakaoTalkIcon.png
  sprint1and2/img/bottomimg.png
  sprint1and2/img/faceBookIcon.png
  sprint1and2/img/footerimg.png
  sprint1and2/img/instagramIcon.png
  sprint1and2/img/mainContent01.png
  sprint1and2/img/mainContent02.png
  sprint1and2/img/mainContent03.png
  sprint1and2/img/mainimg.png
  sprint1and2/img/pandalogo.png
  sprint1and2/img/twitterIcon.png
  sprint1and2/img/youTubeIcon.png
  sprint1and2/index.html
  sprint1and2/index.js
  sprint1and2/indexstyle.css
  sprint1and2/item.html
  sprint1and2/login.html
  sprint1and2/loginstyle.css
  sprint1and2/privacy.html
  sprint1and2/reset.css
  sprint1and2/signup.html
  sprint1and2/signupStyle.css
Labels: 매운맛 🔥, 최종 제출

#29 [김경호] sprint 1+2
  README.md
  faq/faq.html
  img/facebook.png
  img/footer_section.png
  img/instagram.png
  img/logo.png
  img/main1.png
  img/main2.png
  img/main3.png
  img/panda_logo.png
  img/section_top.png
  img/twitter.png
  img/youtube.png
  index.html
  items/items.html
  login/eye.png
  login/google.png
  login/kakao.png
  login/login.html
  login/pandamarket.png
  login/style_login.css
  privacy/privacy.html
  sign_up/sign_up.html
  sign_up/style_signup.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#13 [강명곤] Sprint 1&2
  README.md
  faq/index.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/closed-eyes.png
  image/homepage-logo.png
  image/ic_facebook.png
  image/ic_google.png
  image/ic_instagram.png
  image/ic_kakao.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/loginpage-logo.png
  image/open-eyes.png
  index.html
  items/index.html
  login/index.html
  login/style.css
  privacy/index.html
  reset.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#18 [김민선] sprint 1 + 2
  .vscode/settings.json
  README.md
  css/login.css
  css/reset.css
  css/signUp.css
  css/style.css
  faq.html
  image/home/facebookImg.png
  image/home/homeBottom.png
  image/home/homeTop.png
  image/home/instagramImg.png
  image/home/logo.png
  image/home/middleImg1.png
  image/home/middleImg2.png
  image/home/middleImg3.png
  image/home/twitterImg.png
  image/home/youtubeImg.png
  image/login/google.png
  image/login/homeLogoImg.png
  image/login/kakao.png
  image/signUp/google.png
  image/signUp/kakao.png
  image/signUp/signUpLogoImg.png
  index.html
  items.html
  login.html
  privacy.html
  signUp.html
Labels: 매운맛 🔥, 최종 제출

#32 [오성현] Sprint1+2
  .DS_Store
  card1.png
  card2.png
  card3.png
  facebook.png
  faq/index.html
  img/.DS_Store
  img/landing/.DS_Store
  img/landing/Frame 2608833.png
  img/landing/Frame 2608836.png
  img/landing/Group 33682.png
  img/landing/Img_home_02.png
  img/landing/Img_home_bottom.png
  index.html
  instagram.png
  items/index.html
  login/.DS_Store
  login/bigLogo.png
  login/googleLogin.png
  login/index.html
  login/kakaoLogin.png
  login/login.css
  logo.png
  logo_group.png
  panda1.png
  panda2.png
  privacy/index.html
  signup/index.html
  signup/signup.css
  style.css
  twitter.png
  youtube.png
Labels: 매운맛 🔥, 최종 제출

#15 [김재원] Sprint 1 + 2
  README.md
  ROKAF Sans.ttf
  faq/index.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/eye.png
  image/google.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/kakao.png
  image/panda.png
  image/panda_2.png
  index.html
  items/index.html
  login/index.html
  login/style.css
  privacy/index.html
  reset.css
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#11 [이도엽] Sprint 1 & 2
  README.md
  faq/faq.html
  img/eyeshape.png
  img/footer.png
  img/google.png
  img/googleIcon.png
  img/header.png
  img/ic_facebook.jpg
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakao.png
  img/kakaoIcon.png
  img/logo.png
  img/panda.png
  img/pandaFace.png
  img/section 1.png
  img/section 2.png
  img/section 3.png
  img/랜딩 페이지.jpg
  index.css
  index.html
  index.js
  items/index.html
  login/login.css
  login/login.html
  privacy/privacy.html
  reset.css
  signup/signup.css
  signup/signup.html
Labels: 매운맛 🔥, 최종 제출

#33 [공승훈] sprint1+2
  faq.html
  img/Component 2.png
  img/Component 3.png
  img/Group 19.png
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/btn_visibility_off_24px.svg
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/logo.png
  img/판다 얼굴.png
  index.html
  item.html
  login.html
  privacy.html
  signup.html
  style/README.md
  style/login.css
  style/reset.css
  style/signup.css
  style/style.css
  style/variables.css
Labels: 매운맛 🔥, 최종 제출

#34 [김영은] Sprint 1&2
  .vscode/settings.json
  index.html
  login/images/toggle-show-password-image.png
  login/index.html
  login/style.css
  signup/images/toggle-show-password-image.png
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#41 [김태영] Sprint 3
  index.html
  login/index.html
  signup/index.html
  src/Image/Property 1=md.png
  src/Image/small_logo.png
  src/css/button.css
  src/css/global.css
  src/css/header.css
  src/css/landing.css
  src/css/login.css
  src/css/modal.css
  src/css/signpage.css
  src/css/signup.css
  src/css/style_login.css
  src/css/style_root.css
  src/css/style_signup.css
  src/css/viewport.css
  src/js/landing.js
  src/js/login.js
  src/js/package.json
  src/js/signup.js
  src/js/verification.js
Labels: 매운맛 🔥, 최종 제출

#52 [서유림] Sprint 3
  .vscode/launch.json
  commonValidate.js
  images/btn_visibility_off_24px.svg
  images/btn_visibility_on_24px.svg
  images/favicon.ico
  index.html
  login/index.html
  login/login.css
  login/login.js
  signup/index.html
  signup/signup.css
  signup/signup.js
  style.css
Labels: 순한맛 🐑, 최종 제출

#53 [신지원] Sprint 3
  .gitignore
  index.html
  items.html
  login.css
  login/login.css
  login/login.html
  login/login.js
  login/login.mjs
  login/signin.html
  login/signin.js
  main.css
  package.json
  reset.css
Labels: 매운맛 🔥, 최종 제출

#59 [김청운] sprint1+2
  .vscode/settings.json
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/icons/eye-invisible.svg
  images/icons/eye-visible.svg
  images/logo/favicon.ico
  images/logo/logo.svg
  images/social/facebook-logo.svg
  images/social/google-logo.png
  images/social/instagram-logo.svg
  images/social/kakao-logo.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/판다 얼굴.png
  index.html
  login.html
  style.css
  styles/auth.css
  styles/global.css
  styles/home.css
  test.txt
Labels: 제출일 이후 제출한PR

#68 [김경호] sprint 3
  index.html
  login/login.html
  login/login.js
  login/style_login.css
  sign_up/sign_up.html
  sign_up/sign_up.js
  sign_up/style_signup.css
Labels: 매운맛 🔥, 최종 제출

#44 [이예린] Sprint3
  .DS_Store
  .vscode/launch.json
  assets_panda/.DS_Store
  color.css
  faq.html
  index.html
  index.js
  items.html
  login.css
  login.html
  login.js
  login_create_account_asset/.DS_Store
  login_create_account_asset/btn_visibility_off_24px.svg
  privacy.html
  reset.css
  signup.css
  signup.html
  signup.js
  style-copy.css
  style.css
  style_login.css
  style_signup.css
Labels: 순한맛 🐑, 최종 제출

#66 [김민선] sprint3
  .vscode/settings.json
  README.md
  css/index.css
  css/login.css
  css/signUp.css
  index.html
  js/login.js
  js/signUp.js
  login.html
  signUp.html
Labels: 매운맛 🔥, 최종 제출

#70 [이동훈] Sprint3
  README.md
  Sprint1&2/README.md
  login/login.css
  login/login.html
  login/login.js
  signup/signup.css
  signup/signup.html
  signup/signup.js
Labels: 순한맛 🐑, 최종 제출

#37 [서지우] Sprint 3
  README.md
  index.html
  index.js
Labels: 매운맛 🔥, 진행중

#67 [천우승] Sprint3
  images/image copy 2.png
  images/image copy 3.png
  images/image copy.png
  images/image.png
  images/image_google.png
  images/image_kakao.png
  images/logo.png
  images/panda1.png
  images/panda2.png
  images/panda3.png
  images/panda4.png
  images/panda5.png
  index.css
  index.html
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
Labels: 매운맛 🔥, 최종 제출

#62 [양가현] Sprint3
  README.md
  faq.html
  index.html
  items.html
  js/login.js
  js/sign.js
  js/signup.js
  login.html
  privacy.html
  signup.html
  styles/reset.css
  styles/sign.css
Labels: 매운맛 🔥, 최종 제출

#38 [강명곤] Sprint3
  README.md
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/homepage_logo.png
  image/logoText.png
  image/mainLogo.png
  image/tabletImgHome01.png
  image/tabletImgHome02.png
  image/tabletImgHome03.png
  index.html
  index.js
  login/index.html
  login/index.js
  login/mobile.css
  login/style.css
  login/tablet.css
  mobile.css
  module.js
  package.json
  signup/index.html
  signup/index.js
  signup/mobile.css
  signup/style.css
  signup/tablet.css
  style.css
  tablet.css
Labels: 매운맛 🔥, 최종 제출

#42 [이도엽] Sprint 3
  index.css
  index.html
  login/login.css
  login/login.html
  login/login.js
  module.js
  node_modules/unit-fns/src/index.ts
  node_modules/unit-fns/src/lib/binary.ts
  node_modules/unit-fns/src/lib/number.ts
  node_modules/unit-fns/src/lib/other.ts
  node_modules/unit-fns/src/lib/unary.ts
  package.json
  signup/signup.css
  signup/signup.html
  signup/signup.js
Labels: 매운맛 🔥, 최종 제출
