Repository codeit-sprint-fullstack/2-Sprint-Mission-FE, pull requests merged in 2024-10, with the labels that each got.

#144 [김영은] Sprint 6
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  src/Main.js
  src/api.js
  src/assets/bottom-banner.png
  src/assets/main-banner.png
  src/assets/sbanner1.png
  src/assets/sbanner2.png
  src/assets/sbanner3.png
  src/assets/select-arrow.png
  src/assets/sort-icon.png
  src/assets/x-icon.png
  src/components/AllProducts.js
  src/components/AllProducts.module.css
  src/components/Button.js
  src/components/Button.module.css
  src/components/Container.js
  src/components/Container.module.css
  src/components/Footer.js
  src/components/Nav.js
  src/components/Nav.module.css
  src/contexts/viewportContext.js
  src/hook/useAsync.js
  src/hook/useRegisterValidation.js
  src/pages/HomePage.js
  src/pages/HomePage.module.css
  src/pages/RegistrationPage.js
  src/pages/RegistrationPage.module.css
  src/pages/SecondhandMarket.js
Labels: 매운맛 🔥, 제출일 이후 제출한PR

#138 [천우승] Sprint6
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/Market.js
  src/Registration.js
  src/Rendering.css
  src/Rendering.js
  src/api/itemApi.js
  src/assets/images/icons/arrow_left.svg
  src/assets/images/icons/arrow_right.svg
  src/assets/images/icons/ic_arrow_down.svg
  src/assets/images/icons/ic_heart.svg
  src/assets/images/icons/ic_search.svg
  src/assets/images/icons/ic_sort_mobile.svg
  src/assets/images/logo/logo.svg
  src/components/Layout/Header.css
  src/components/Layout/Header.jsx
  src/components/UI/Button.jsx
  src/components/UI/DropdownList.css
  src/components/UI/DropdownList.jsx
  src/components/UI/PaginationBar.css
  src/components/UI/PaginationBar.jsx
  src/index.js
  src/pages/AdditemPage/AddItemPage.css
  src/pages/AdditemPage/AddItemPage.jsx
  src/pages/AdditemPage/components/AddItemsSection.jsx
  src/pages/HomePage/Footer.js
  src/pages/HomePage/Header.js
  src/pages/HomePage/Main1.js
  src/pages/HomePage/Main2.js
  src/pages/HomePage/Main3.js
  src/pages/HomePage/Main4.js
  src/pages/HomePage/Main5.js
  src/pages/HomePage/images/image copy 2.png
  src/pages/HomePage/images/image copy 3.png
  src/pages/HomePage/images/image copy.png
  src/pages/HomePage/images/image.png
  src/pages/HomePage/images/image_google.png
  src/pages/HomePage/images/image_kakao.png
  src/pages/HomePage/images/logo.png
  src/pages/HomePage/images/panda1.png
  src/pages/HomePage/images/panda2.png
  src/pages/HomePage/images/panda3.png
  src/pages/HomePage/images/panda4.png
  src/pages/HomePage/images/panda5.png
  src/pages/MarketPage/MarketPage.css
  src/pages/MarketPage/MarketPage.js
  src/pages/MarketPage/components/AllItemsSection.jsx
  src/pages/MarketPage/components/ItemCard.jsx
  src/styles/global.css
Labels: 매운맛 🔥, 최종 제출

#153 [방신철] sprint8
  .github/workflows/auto-label-assign.yml
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  components/ArticleBestList.js
  components/ArticleBestList.module.css
  components/ArticleList.js
  components/ArticleList.module.css
  components/Comment.js
  components/Comment.module.css
  components/Dropdown.js
  components/Dropdown.module.css
  components/Footer.js
  components/Footer.module.css
  components/Header.js
  components/Header.module.css
  components/Search.js
  components/Search.module.css
  jsconfig.json
  lib/axios.js
  lib/formatDate.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/articles/[id].js
  pages/articles/[id]/patch.js
  pages/index.js
  pages/register.js
  styles/Article.module.css
  styles/Home.module.css
  styles/globals.css
  styles/register.module.css
Labels: 매운맛 🔥, 최종 제출

#147 [김영은] Sprint 8
  .eslintrc.json
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  components/ArticleList.js
  components/ArticleList.module.css
  components/BestArticle.js
  components/BestArticle.module.css
  components/Button.js
  components/Button.module.css
  components/CommentList.js
  components/CommentList.module.css
  components/Footer.js
  components/Footer.module.css
  components/GNB.js
  components/GNB.module.css
  components/KebabMenu.js
  components/KebabMenu.module.css
  jsconfig.json
  lib/axios.js
  lib/formatDate.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/board/[id]/edit.js
  pages/board/[id]/index.js
  pages/board/index.js
  pages/board/newArticle.js
  pages/index.js
  pages/items.js
  public/bottom-banner.png
  public/favicon.ico
  public/ic_arrow_down.png
  public/ic_back.png
  public/ic_facebook.png
  public/ic_heart.png
  public/ic_instagram.png
  public/ic_kebab.png
  public/ic_medal.png
  public/ic_profile.png
  public/ic_search.png
  public/ic_sort.png
  public/ic_twitter.png
  public/ic_youtube.png
  public/logo_1.png
  public/logo_2.png
  public/main-banner.png
  public/no_image.png
  public/reply_empty.png
  public/sbanner1.png
  public/sbanner2.png
  public/sbanner3.png
  styles/Home.module.css
  styles/article.module.css
  styles/board.module.css
  styles/globals.css
  styles/newArticle.module.css
Labels: 매운맛 🔥, 최종 제출

#157 [서지우] sprint8
  .eslintrc.json
  .gitignore
  README.md
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/hello.js
  pages/fonts/GeistMonoVF.woff
  pages/fonts/GeistVF.woff
  pages/index.js
  public/favicon.ico
  styles/Home.module.css
  styles/globals.css
Labels: 순한맛 🐑, 진행중

#150 [이도엽] Sprint 8
  next-sprint/.eslintrc.json
  next-sprint/.gitignore
  next-sprint/README.md
  next-sprint/components/ArticleDetail.js
  next-sprint/components/ArticleDetail.module.css
  next-sprint/components/ArticleDropdown.js
  next-sprint/components/ArticleDropdown.module.css
  next-sprint/components/ArticleList.js
  next-sprint/components/ArticleList.module.css
  next-sprint/components/ArticleReview.js
  next-sprint/components/ArticleReview.module.css
  next-sprint/components/ArticleReviewDropdown.js
  next-sprint/components/Dropdown.js
  next-sprint/components/Dropdown.module.css
  next-sprint/components/Footer.js
  next-sprint/components/Footer.module.css
  next-sprint/components/Nav.js
  next-sprint/components/Nav.module.css
  next-sprint/components/PatchInput.js
  next-sprint/components/RecentArticle.js
  next-sprint/components/RecentArticle.module.css
  next-sprint/components/RegisterInput.js
  next-sprint/components/RegisterInput.module.css
  next-sprint/components/SearchForm.js
  next-sprint/components/SearchForm.module.css
  next-sprint/jsconfig.json
  next-sprint/next.config.mjs
  next-sprint/package-lock.json
  next-sprint/package.json
  next-sprint/pages/_app.js
  next-sprint/pages/_document.js
  next-sprint/pages/articles/[id].js
  next-sprint/pages/index.js
  next-sprint/pages/patchArticle/[id].js
  next-sprint/pages/registerArticle.js
  next-sprint/public/images/Img_reply_empty.svg
  next-sprint/public/images/ic_arrow_down.svg
  next-sprint/public/images/ic_back.svg
  next-sprint/public/images/ic_facebook.svg
  next-sprint/public/images/ic_heart.svg
  next-sprint/public/images/ic_instagram.svg
  next-sprint/public/images/ic_kebab.svg
  next-sprint/public/images/ic_profile.svg
  next-sprint/public/images/ic_search.svg
  next-sprint/public/images/ic_twitter.svg
  next-sprint/public/images/ic_youtube.svg
  next-sprint/public/images/img_badge.svg
  next-sprint/public/images/nav_panda.svg
  next-sprint/public/images/nav_panda_mobile.svg
  next-sprint/public/images/sample_img.svg
  next-sprint/styles/Home.module.css
  next-sprint/styles/globals.css
  next-sprint/styles/variable.css
Labels: 매운맛 🔥, 최종 제출

#158 [현준배] Sprint8
  .DS_Store
  sprint8/.eslintrc.json
  sprint8/.gitignore
  sprint8/README.md
  sprint8/jsconfig.json
  sprint8/next.config.mjs
  sprint8/package-lock.json
  sprint8/package.json
  sprint8/pages/_app.js
  sprint8/pages/_document.js
  sprint8/pages/api/hello.js
  sprint8/pages/index.js
  sprint8/public/images/Img_home_bottom.png
  sprint8/public/images/Img_home_top.png
  sprint8/public/images/btn_sort.png
  sprint8/public/images/btn_visibility.png
  sprint8/public/images/btn_visibility_off_24px.svg
  sprint8/public/images/btn_visibility_on_24px.svg
  sprint8/public/images/ic_facebook.png
  sprint8/public/images/ic_google.png
  sprint8/public/images/ic_instagram.png
  sprint8/public/images/ic_kakaotalk.png
  sprint8/public/images/ic_twitter.png
  sprint8/public/images/ic_youtube.png
  sprint8/public/images/img_default_product.png
  sprint8/public/images/img_hot-item.png
  sprint8/public/images/img_register.png
  sprint8/public/images/img_search.png
  sprint8/public/images/logo_gnb.png
  sprint8/public/images/logo_gnb_m.png
  sprint8/public/images/logo_subpage.png
  sprint8/public/images/pandamarket.png
  sprint8/public/images/user_profile.png
  sprint8/public/images/warn.svg
  sprint8/styles/globals.css
  sprint8/styles/variables.css
  test
Labels: 순한맛 🐑, 미완성

#151 [김민선] Sprint8
  .eslintrc.json
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  .vscode/settings.json
  README.md
  components/BestPost.js
  components/Footer.js
  components/Header.js
  components/PostList.js
  components/SearchBar.js
  jsconfig.json
  lib/api.js
  lib/articleApi.js
  lib/axios.js
  lib/handleError.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/community.js
  pages/createPost.js
  pages/index.js
  pages/posts/[id].js
  pages/search.js
  public/bestImg.png
  public/bigHeart.png
  public/defaultImg.png
  public/facebookIcon.png
  public/instagramIcon.png
  public/logoImg.png
  public/searchIcon.png
  public/smallArrow.png
  public/smallHeart.png
  public/smallLogoImg.png
  public/toggleArrow.png
  public/twitterIcon.png
  public/userIcon.png
  public/youtubeIcon.png
  styles/Header.module.css
  styles/bestPost.module.css
  styles/community.module.css
  styles/footer.module.css
  styles/globals.css
  styles/postList.module.css
  styles/reset.css
  styles/searchBar.module.css
Labels: 매운맛 🔥, 진행중

#160 [김태연] Spinrt8
  .eslintrc.json
  .gitignore
  README.md
  components/CommentItem.js
  components/EditDeleteDropDown.js
  components/Footer.js
  components/Nav.js
  components/Section.js
  components/SortSelector.js
  components/ValidatedInputBox.js
  hooks/useDataFetch.js
  hooks/useDataFetchNew.js
  hooks/useResponsiveItemCount.js
  jsconfig.json
  lib/axios.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/faq.js
  pages/freeboard/[id].js
  pages/freeboard/index.js
  pages/freeboard/write/[[...slug]].js
  pages/index.js
  pages/items/[id].js
  pages/items/index.js
  pages/privacy-policy.js
  pages/register.js
  postcss.config.js
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  public/images/arrow_left.png
  public/images/arrow_right.png
  public/images/check_section.png
  public/images/default.png
  public/images/ic_X.png
  public/images/ic_back.png
  public/images/ic_bigheart.png
  public/images/ic_facebook.png
  public/images/ic_heart.png
  public/images/ic_instagram.png
  public/images/ic_kebab.png
  public/images/ic_profile.png
  public/images/ic_search.png
  public/images/ic_twitter.png
  public/images/ic_youtube.png
  public/images/img_badge.png
  public/images/logo.png
  public/images/mobile_arrow.png
  public/images/pc_arrow.png
  public/images/register_section.png
  public/images/safety_section.png
  public/images/search_section.png
  public/images/watch_section.png
  styles/globals.css
  tailwind.config.js
  utils/convertDate.js
Labels: 매운맛 🔥, 최종 제출
