Repository codeit-sprint-fullstack/2-Sprint-Mission-FE, pull requests merged in 2024-09, with the labels that each got.

#72 [김태영] sprint4
  .gitignore
  package-lock.json
  package.json
  src/js/ArticleService.js
  src/js/ProductService.js
  src/js/main.js
  src/js/package.json
Labels: 매운맛 🔥, 최종 제출

#75 [서유림] Sprint 4
  .gitignore
  Sprint4/ArticleService.js
  Sprint4/ProductService.js
  Sprint4/main.js
  package-lock.json
  package.json
Labels: 순한맛 🐑, 최종 제출

#78 [신지원] Sprint4
  .gitignore
  api/ArticleService.js
  api/ProductService.js
  api/api.mjs
  login/login.css
  login/login.js
  login/login.mjs
  login/signin.js
  main.js
  package-lock.json
  package.json
Labels: 매운맛 🔥, 최종 제출

#86 [소재희] sprint4
  README.md
  inc/head.js
  index.html
  js/api/ArticleService.js
  js/api/ProductService.js
  js/auth.js
  js/main.js
  js/module/authUtils.js
  package.json
Labels: 매운맛 🔥, 최종 제출

#64 [김영은] Sprint 3
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  .vscode/settings.json
  api/ArticleService.js
  api/ProductService.js
  api/main.js
  api/package-lock.json
  api/package.json
  bottom-banner.png
  index.html
  login/index.html
  login/index.js
  login/style.css
  logo.png
  logo_1.png
  logo_2.png
  signup/index.html
  signup/index.js
  signup/style.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#69 [김태연] Sprint3
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  image-sprint2/Component_2.png
  image-sprint2/Component_3.png
  index.html
  items.html
  login.css
  login.html
  login.js
  package-lock.json
  package.json
  reset.css
  signup.css
  signup.html
  signup.js
  style.css
  validation.js
Labels: 매운맛 🔥, 최종 제출

#71 [김은효] sprint3
  README.md
  판다마켓/faq/index.html
  판다마켓/img/Img_home_01.png
  판다마켓/img/Img_home_02.png
  판다마켓/img/Img_home_03.png
  판다마켓/img/Img_home_bottom.png
  판다마켓/img/Img_home_top.png
  판다마켓/img/Property 1=sm.png
  판다마켓/img/Property_1=sm.png
  판다마켓/img/ic_facebook.png
  판다마켓/img/ic_instagram.png
  판다마켓/img/ic_twitter.png
  판다마켓/img/ic_youtube.png
  판다마켓/index.html
  판다마켓/items/index.html
  판다마켓/login/IMG/Component 2.png
  판다마켓/login/IMG/Component 3.png
  판다마켓/login/IMG/btn_visibility_on_24px.svg
  판다마켓/login/IMG/logo.png
  판다마켓/login/index.html
  판다마켓/login/index.js
  판다마켓/login/style.css
  판다마켓/privacy/index.html
  판다마켓/signup/IMG/Component 2.png
  판다마켓/signup/IMG/Component 3.png
  판다마켓/signup/IMG/btn_visibility_on_24px.svg
  판다마켓/signup/IMG/logo.png
  판다마켓/signup/index.html
  판다마켓/signup/style.css
  판다마켓/style.css
Labels: 매운맛 🔥, 미완성

#93 [현준배] Sprint 4
  JavaScript/auth.js
  index.html
  login.html
  styles/home.css
Labels: 미완성

#96 [김경호] Sprint 4
  api/ArticleService.js
  api/ProductService.js
  api/api.mjs
  index.html
  login/login.html
  login/login.js
  login/login.mjs
  login/style_login.css
  sign_up/sign_up.html
  sign_up/sign_up.js
  sign_up/sign_up.mjs
  sign_up/style_signup.css
  style.css
Labels: 매운맛 🔥, 최종 제출

#85 [강명곤] sprint 4
  .gitignore
  package-lock.json
  package.json
  sprint4/ArticleService.js
  sprint4/ProductService.js
  sprint4/main.js
Labels: 매운맛 🔥, 최종 제출

#81 [이도엽] Sprint4
  .gitignore
  README.md
  api/ArticleService.js
  api/ProductService.js
  api/main.js
  login/login.js
  module.js
  node_modules/unit-fns/src/index.ts
  node_modules/unit-fns/src/lib/binary.ts
  node_modules/unit-fns/src/lib/number.ts
  node_modules/unit-fns/src/lib/other.ts
  node_modules/unit-fns/src/lib/unary.ts
  signup/signup.js
Labels: 매운맛 🔥, 최종 제출

#124 [김영은] Sprint 5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/Main.js
  src/api.js
  src/assets/arrow-left.png
  src/assets/arrow-right.png
  src/assets/default-image.png
  src/assets/ic_facebook.png
  src/assets/ic_instagram.png
  src/assets/ic_twitter.png
  src/assets/ic_youtube.png
  src/assets/logo_1.png
  src/assets/logo_2.png
  src/assets/profile-icon.png
  src/assets/search-icon.png
  src/assets/sort-icon.png
  src/components/AllProducts.js
  src/components/AllProducts.module.css
  src/components/App.js
  src/components/App.module.css
  src/components/BestProducts.js
  src/components/BestProducts.module.css
  src/components/Container.js
  src/components/Container.module.css
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/Nav.js
  src/components/Nav.module.css
  src/hook/useAsync.js
  src/index.js
  src/pages/SecondhandMarket.js
Labels: 매운맛 🔥, 진행중

#114 [양가현] Sprint5
  .github/pull-request-template.md
  .github/workflows/delete-merged-branch-config.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/api/axiosInstance.js
  src/components/BestProduct.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/ProductList.jsx
  src/css/BestProduct.css
  src/css/Footer.css
  src/css/Header.css
  src/css/ProductList.css
  src/images/etc/likeButton.svg
  src/images/etc/nonImage.svg
  src/images/etc/reading-glasses.svg
  src/images/etc/userIcon.svg
  src/images/icon/facebook.png
  src/images/icon/instagram.png
  src/images/icon/pandalogo.svg
  src/images/icon/twitter.png
  src/images/icon/youtube.png
  src/index.js
Labels: 매운맛 🔥, 최종 제출

#108 [공승훈] sprint5
  .gitignore
  package-lock.json
  package.json
  public/favicon.svg
  public/index.html
  src/App.css
  src/App.js
  src/components/BestProductList.css
  src/components/BestProductList.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/ProductCard.css
  src/components/ProductCard.js
  src/components/ProductList.css
  src/components/ProductList.js
  src/components/img/Frame 2609463.svg
  src/components/img/Group 19.svg
  src/components/img/arrow_left.svg
  src/components/img/arrow_right.svg
  src/components/img/ic_arrow_down.svg
  src/components/img/ic_facebook.svg
  src/components/img/ic_heart.svg
  src/components/img/ic_instagram.svg
  src/components/img/ic_search.svg
  src/components/img/ic_sort.svg
  src/components/img/ic_twitter.svg
  src/components/img/ic_youtube.svg
  src/components/img/img_default.svg
  src/components/img/판다마켓.svg
  src/hooks/useProducts.js
  src/index.js
  src/styles/reset.css
  src/styles/variables.css
Labels: 매운맛 🔥, 최종 제출

#97 [현준배] Sprint 5
  gitPushTest.index
  index.html
  sprint5/.gitignore
  sprint5/.vscode/settings.json
  sprint5/README.md
  sprint5/package-lock.json
  sprint5/package.json
  sprint5/public/index.html
  sprint5/src/App.js
  sprint5/src/assets/bottom-banner-image.png
  sprint5/src/assets/eye-invisible.svg
  sprint5/src/assets/eye-visible.svg
  sprint5/src/assets/facebook-logo.svg
  sprint5/src/assets/favicon.ico
  sprint5/src/assets/feature1-image.png
  sprint5/src/assets/feature2-image.png
  sprint5/src/assets/feature3-image.png
  sprint5/src/assets/google-logo.png
  sprint5/src/assets/hero-image.png
  sprint5/src/assets/instagram-logo.svg
  sprint5/src/assets/kakao-logo.png
  sprint5/src/assets/logo.svg
  sprint5/src/assets/twitter-logo.svg
  sprint5/src/assets/youtube-logo.svg
  sprint5/src/components/BestProducts.js
  sprint5/src/components/Footer.js
  sprint5/src/components/Header.js
  sprint5/src/components/Pagination.js
  sprint5/src/components/ProductCard.js
  sprint5/src/components/ProductsList.js
  sprint5/src/index.js
  sprint5/src/styles/BestProducts.css
  sprint5/src/styles/Footer.css
  sprint5/src/styles/Header.css
  sprint5/src/styles/Pagination.css
  sprint5/src/styles/ProductCard.css
  sprint5/src/styles/ProductsList.css
Labels: 미완성

#79 [김영은] Sprint 4
  README.md
  api/ArticleService.js
  api/ProductService.js
  api/ValidateData.js
  api/main.js
  faq/index.html
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  items/index.html
  login-button.png
  login/images/google.png
  login/images/kakao.png
  login/images/logo.png
  login/images/toggle-show-password-image.png
  main-banner.png
  privacy/index.html
  reset.css
  sbanner1.png
  sbanner2.png
  sbanner3.png
  shop-button.png
  signup/images/google.png
  signup/images/kakao.png
  signup/images/logo.png
  signup/images/toggle-show-password-image.png
Labels: 매운맛 🔥, 최종 제출

#98 [김태연] Sprint4
  .gitignore
  ArticleService.js
  ProductService.js
  README.md
  main.js
  package-lock.json
  package.json
Labels: 매운맛 🔥, 최종 제출

#120 [김재원] Sprint4
  .DS_Store
  README.md
  api/ArticleService.js
  api/ProductService.js
  api/main.js
  login/style.css
  package-lock.json
  package.json
  signup/signup.js
Labels: 제출일 이후 제출한PR, 최종 제출

#104 [소재희] sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  src/api/ProductService.js
  src/assets/images/btn_sort.png
  src/assets/images/icon/ic_facebook.png
  src/assets/images/icon/ic_google.png
  src/assets/images/icon/ic_heart.png
  src/assets/images/icon/ic_instagram.png
  src/assets/images/icon/ic_kakaotalk.png
  src/assets/images/icon/ic_search.png
  src/assets/images/icon/ic_twitter.png
  src/assets/images/icon/ic_youtube.png
  src/assets/images/logo_gnb.png
  src/assets/images/logo_gnb_m.png
  src/assets/images/user_profile.png
  src/components/App.css
  src/components/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/ProductMain/BestProductList.css
  src/components/ProductMain/BestProductList.js
  src/components/ProductMain/Pagination.css
  src/components/ProductMain/Pagination.js
  src/components/ProductMain/ProductItem.css
  src/components/ProductMain/ProductItem.js
  src/components/ProductMain/ProductList.css
  src/components/ProductMain/ProductList.js
  src/components/ProductMain/ProductMain.css
  src/components/ProductMain/ProductMain.js
  src/hooks/useFetchProducts.js
  src/index.css
  src/index.js
Labels: 매운맛 🔥, 최종 제출

#100 [신지원] Sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/api/ProductService.js
  src/api/api.js
  src/assets/fonts/ROKAFSans.ttf
  src/assets/img/arrow_left.png
  src/assets/img/arrow_right.png
  src/assets/img/ic_arrow_down.png
  src/assets/img/ic_facebook.png
  src/assets/img/ic_instagram.png
  src/assets/img/ic_search.png
  src/assets/img/ic_sort.png
  src/assets/img/ic_twitter.png
  src/assets/img/ic_youtube.png
  src/assets/img/img_default.png
  src/assets/img/landing/Img_home_01.png
  src/assets/img/landing/Img_home_02.png
  src/assets/img/landing/Img_home_03.png
  src/assets/img/landing/Img_home_bottom.png
  src/assets/img/landing/Img_home_top.png
  src/assets/img/login/btn_visibility_on.png
  src/assets/img/login/google.png
  src/assets/img/login/kakao.png
  src/assets/img/login/판다 얼굴.png
  src/assets/img/판다 얼굴.png
  src/component/App.js
  src/component/BestItem.js
  src/component/Footer.js
  src/component/ItemList.js
  src/component/Nav.js
  src/component/Pagination.js
  src/css/App.css
  src/css/BestItem.css
  src/css/Footer.css
  src/css/ItemList.css
  src/css/Nav.css
  src/css/Pagination.css
  src/index.js
Labels: 매운맛 🔥, 최종 제출

#106 [강명곤] sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/PriceUtils.js
  src/api.js
  src/components/App.js
  src/components/BestProduct.js
  src/components/Footer.js
  src/components/Nav.js
  src/components/Pagination.js
  src/components/ProductItem.js
  src/components/SalesProduct.js
  src/components/SalesProductTitle.js
  src/components/SortOrder.js
  src/css/App.css
  src/css/BestProduct.css
  src/css/Footer.css
  src/css/Nav.css
  src/css/Pagination.css
  src/css/ProductItem.css
  src/css/SalesProduct.css
  src/css/SalesProductTitle.css
  src/css/SortOrder.css
  src/image/btn_sort.png
  src/image/homepage-logo.png
  src/image/homepage_logo.png
  src/image/ic_arrow_down.png
  src/image/ic_facebook.png
  src/image/ic_google.png
  src/image/ic_instagram.png
  src/image/ic_kakao.png
  src/image/ic_search.png
  src/image/ic_twitter.png
  src/image/ic_youtube.png
  src/image/loginpage-logo.png
  src/image/logoText.png
  src/image/mainLogo.png
  src/image/profileImg.png
  src/index.js
  src/reset.css
Labels: 매운맛 🔥, 최종 제출

#127 [방신철] sprint6
  .gitignore
  README.md
  build/asset-manifest.json
  build/static/css/main.982852d3.css
  build/static/css/main.982852d3.css.map
  build/static/js/main.a51c24bf.js
  build/static/js/main.a51c24bf.js.LICENSE.txt
  build/static/js/main.a51c24bf.js.map
  build/static/media/bottom-banner-image.8696c1540dcf8b237d32.png
  build/static/media/feature1-image.3e574a8b7737034aaab5.png
  build/static/media/feature2-image.cfbb0bc80bfee15d47dd.png
  build/static/media/feature3-image.62f9afc71f3c80ea5974.png
  build/static/media/hero-image.f15c969c4b6c73d0912d.png
  build/static/media/logo.29ee34c66503696401bf.svg
  build/static/media/logo.29ee34c66503696401bf52499bb104fb.svg
  package-lock.json
  package.json
  src/App.js
  src/Main.js
  src/component/BestProductList.js
  src/component/Footer.js
  src/component/ItemList.css
  src/component/ItemList.js
  src/component/Nav.js
  src/component/PageButton.js
  src/component/PandaApi.js
  src/component/Product.js
  src/component/ProductList.js
  src/component/ProductMenuContainer.js
  src/component/TestFile.js
  src/component/api.js
  src/index.css
  src/index.js
  src/page/DetailPage.js
  src/page/Footer.js
  src/page/HomePage.js
  src/page/HomeStyle/auth.css
  src/page/HomeStyle/global.css
  src/page/HomeStyle/home.css
  src/page/HomeStyle/modal.css
  src/page/Items.js
  src/page/PageNav.js
  src/page/Registration.css
  src/page/Registration.js
  src/style/BestProductList.css
  src/style/Footer.css
  src/style/Nav.css
  src/style/PageButton.css
  src/style/ProductList.css
  styles/global.css
  styles/home.css
Labels: 매운맛 🔥, 최종 제출

#129 [김민선]Sprint5
  .gitignore
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/img/facebookIcon.png
  public/img/heart.png
  public/img/instagramIcon.png
  public/img/logoImg.png
  public/img/search.png
  public/img/twitterIcon.png
  public/img/youtubeIcon.png
  public/index.html
  src/App.js
  src/community.js
  src/components/BestProduct.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Pagination.js
  src/components/ProductContent.js
  src/components/SaleProduct.js
  src/hooks/useMediaQuery.js
  src/index.js
  src/style/BestProduct.css
  src/style/Footer.css
  src/style/Header.css
  src/style/Pagination.css
  src/style/ProductContent.css
  src/style/SaleProduct.css
  src/style/reset.css
Labels: 매운맛 🔥, 제출일 이후 제출한PR, 최종 제출

#136 [강명곤] sprint6
  README.md
  package-lock.json
  package.json
  public/index.html
  src/Main.js
  src/PriceFunc.js
  src/api.js
  src/components/App.js
  src/components/App.module.css
  src/components/BestProduct.js
  src/components/BestProduct.module.css
  src/components/Footer.js
  src/components/Footer.module.css
  src/components/Nav.js
  src/components/Nav.module.css
  src/components/Pagination.js
  src/components/Pagination.module.css
  src/components/ProductItem.js
  src/components/ProductItem.module.css
  src/components/SalesProduct.js
  src/components/SalesProduct.module.css
  src/components/SalesProductTitle.js
  src/components/SalesProductTitle.module.css
  src/components/SortOrder.js
  src/components/SortOrder.module.css
  src/components/Tags.js
  src/components/Tags.module.css
  src/hooks/useValidation.js
  src/image/Img_home_01.png
  src/image/Img_home_02.png
  src/image/Img_home_03.png
  src/image/Img_home_bottom.png
  src/image/Img_home_top.png
  src/image/closed-eyes.png
  src/image/ic_X.png
  src/image/img_default.png
  src/image/open-eyes.png
  src/image/tabletImgHome01.png
  src/image/tabletImgHome02.png
  src/image/tabletImgHome03.png
  src/index.js
  src/pages/BulletinBoardPage.js
  src/pages/FaqPage.js
  src/pages/HomePage.js
  src/pages/HomePage.module.css
  src/pages/ItemsDetailPage.js
  src/pages/ItemsPage.js
  src/pages/ItemsPage.module.css
  src/pages/LogInPage.js
  src/pages/LogInPage.module.css
  src/pages/NotFoundPage.js
  src/pages/PrivacyPage.js
  src/pages/RegistrationPage.js
  src/pages/RegistrationPage.module.css
  src/pages/SignUpPage.js
  src/pages/SignUpPage.module.css
Labels: 매운맛 🔥, 진행중

#123 [양가현] Sprint6
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/api/fetchApi.js
  src/components/Default/Footer.jsx
  src/components/Default/Header.jsx
  src/components/Default/HeaderFooter.css
  src/components/Default/Layout.jsx
  src/components/HomePage/HomePage.jsx
  src/components/HomePage/Homepage.css
  src/components/ProductDetails/ProductDetails.jsx
  src/components/ProductList/ProductList.css
  src/components/ProductList/ProductList.jsx
  src/components/Registration/Registration.css
  src/components/Registration/Registration.jsx
  src/images/etc/delete_icon.svg
  src/images/etc/img_default.svg
  src/images/home/bottom_banner.png
  src/images/home/footer.png
  src/images/home/hotitem.png
  src/images/home/register.png
  src/images/home/search.png
  src/images/home/top_banner.png
  src/index.js
Labels: 매운맛 🔥, 최종 제출
